CREATE TABLE users(
      id NUMBER(*,0)  GENERATED BY DEFAULT AS IDENTITY NOT NULL ENABLE,
      first_name VARCHAR2(50) NOT NULL,
      middle_name VARCHAR2(50) NULL,
      last_name VARCHAR2(50) NOT NULL,
      username VARCHAR2(50) NOT NULL,
      email VARCHAR2(70) NOT NULL,
      mobile_no VARCHAR2(10) NOT NULL,
      is_active NUMBER(1) DEFAULT 1 NOT NULL,
      created_on TIMESTAMP
);

ALTER TABLE users ADD CONSTRAINT "PK_users" PRIMARY KEY ("ID");

INSERT INTO users (first_name, last_name, username, email, mobile_no, is_active, created_on) VALUES('Somnath', 'Shinde', 'somshine', 'soma.shinde@gmail.com', '9665781284', 1, CURRENT_TIMESTAMP);
INSERT INTO users (first_name, last_name, username, email, mobile_no, is_active, created_on) VALUES('Shivank', 'Shinde', 'shiv', 'shiv@gmail.com', '9665781285', 1, CURRENT_TIMESTAMP);
INSERT INTO users (first_name, last_name, username, email, mobile_no, is_active, created_on) VALUES('Kiran', 'Shinde', 'kiran', 'kiran@gmail.com', '9665781286', 1, CURRENT_TIMESTAMP);
commit;

SELECT * FROM users;

CREATE TABLE task_priorities(
     id NUMBER(*,0)  GENERATED BY DEFAULT AS IDENTITY NOT NULL ENABLE,
     name VARCHAR2(600) NOT NULL,
     is_active NUMBER(1) DEFAULT 1 NOT NULL,
     created_on TIMESTAMP
);

ALTER TABLE task_priorities ADD CONSTRAINT "PK_task_priorities" PRIMARY KEY ("ID");

INSERT INTO task_priorities (name, is_active, created_on) VALUES('Low',1, CURRENT_TIMESTAMP);
INSERT INTO task_priorities (name, is_active, created_on) VALUES('Medium', 1, CURRENT_TIMESTAMP);
INSERT INTO task_priorities (name, is_active, created_on) VALUES('High', 1, CURRENT_TIMESTAMP);
commit;

CREATE TABLE task_statues(
     id NUMBER(*,0)  GENERATED BY DEFAULT AS IDENTITY NOT NULL ENABLE,
     name VARCHAR2(600) NOT NULL,
     description VARCHAR2(3000) NULL,
     is_active NUMBER(1) DEFAULT 1 NOT NULL,
     created_on TIMESTAMP
);

ALTER TABLE task_statues ADD CONSTRAINT "PK_task_statues" PRIMARY KEY ("ID");

INSERT INTO task_statues (name, description, is_active, created_on) VALUES('New', 'New', 1, CURRENT_TIMESTAMP);
INSERT INTO task_statues (name, description, is_active, created_on) VALUES('In Progress', 'In Progress', 1, CURRENT_TIMESTAMP);
INSERT INTO task_statues (name, description, is_active, created_on) VALUES('Resolved', 'Resolved', 1, CURRENT_TIMESTAMP);
INSERT INTO task_statues (name, description, is_active, created_on) VALUES('Completed', 'Completed', 1, CURRENT_TIMESTAMP);
INSERT INTO task_statues (name, description, is_active, created_on) VALUES('Closed', 'Closed', 1, CURRENT_TIMESTAMP);
commit;

SELECT * FROM task_statues;

CREATE TABLE user_tasks(
       id NUMBER(*,0)  GENERATED BY DEFAULT AS IDENTITY NOT NULL ENABLE,
       title VARCHAR2(600) NOT NULL,
       description VARCHAR2(3000) NULL,
       task_status_id NUMBER NOT NULL,
       task_priority_id NUMBER NOT NULL,
       assigned_user_id NUMBER NULL,
       due_date TIMESTAMP (6),
       progress NUMBER(3) NULL,
       completed_on TIMESTAMP,
       created_on TIMESTAMP
);

ALTER TABLE user_tasks ADD CONSTRAINT "PK_user_tasks" PRIMARY KEY ("ID");
ALTER TABLE user_tasks ADD CONSTRAINT FK_user_tasks_task_statues FOREIGN KEY (task_status_id) REFERENCES task_statues(ID);
ALTER TABLE user_tasks ADD CONSTRAINT FK_user_tasks_task_priorities FOREIGN KEY (task_priority_id) REFERENCES task_priorities(ID);
ALTER TABLE user_tasks ADD CONSTRAINT FK_user_tasks_users FOREIGN KEY (assigned_user_id) REFERENCES users(ID);

commit;

SELECT * FROM user_tasks;